apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
  namespace: devops
  name: jenkins-kubernetes-ubuntu
spec:
  containers:
    - name: container1
      image: busybox
      command:
        - cat
      tty: true
