apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
  namespace: devops
  name: jenkins-kubernetes-ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - cat
      tty: true
