apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
  namespace: devops
  name: jenkins-kubernetes-ubuntu
spec:
  containers:
    - name: container1
      image: nginx
      command:
        - cat
      tty: true
    - name: container2
      image: ubuntu
      command:
        - cat
      tty: true
    - name: container3
      image: httpd
      command:
        - cat
      tty: true
    - name: container4
      image: debian
      command:
        - cat
      tty: true
