apiVersion: v1
kind: Pod
metadata:
  namespace: devops
spec:
  containers:
    - name: kubectl
      image: ubuntu
      tty: true
      volumeMounts:
        - name: kube_dir
          mountPath: /root/.kube/config
  volumes:
    - name: kube_dir
      hostPath:
        path: /etc/kubernetes/admin.conf